apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
  labels:
    app: weather-api
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: nagarajharsha20/weatherapi
          ports:
            - containerPort: 8080  
          env:
            - name: ENVIRONMENT
              value: "production"
