name: CI Pipelines for Weather API Project

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (you can change this as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub (use secrets for username and password)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Secret for Docker Hub password

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t nagarajharsha20/weatherapi:${{ github.sha }} -f Dockerfile .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push nagarajharsha20/weatherapi:${{ github.sha }}
