name: CI Pipelines for Weather API Project

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub (use secrets for username and password)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Secret for Docker Hub password

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t nagarajharsha20/weatherapi:${{ github.sha }} -f Dockerfile .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push nagarajharsha20/weatherapi:${{ github.sha }}

    - name: Install Rancher CLI
      run: |
        # Download Rancher CLI tarball with wget
        wget https://github.com/rancher/cli/releases/download/v2.6.0/rancher-linux-amd64-v2.6.0.tar.gz
  
        # Check if the file exists
        if [ -f rancher-linux-amd64-v2.6.0.tar.gz ]; then
          echo "Download successful"
        else
          echo "Download failed" && exit 1
        fi
  
        # List downloaded files for debug purposes
        ls -l
  
        # Extract the tarball (correct flag for .tar.gz files)
        tar -xzvf rancher-linux-amd64-v2.6.0.tar.gz
      
        # List the files in the extracted directory to confirm successful extraction
        ls -l rancher-v2.6.0
  
        # Move the Rancher binary to /usr/local/bin
        sudo mv rancher-v2.6.0/rancher /usr/local/bin/rancher
  
        # Verify the Rancher CLI installation
        rancher --version

  


      # Decode kubeconfig and set up kubectl
    - name: Set up Kubernetes config
      run: |
        # Ensure the .kube directory exists
        mkdir -p ~/.kube
    
        # Decode and write the base64-encoded config to ~/.kube/config
         echo "${{ secrets.KUBECONFIG_SECRET }}" | base64 -d > ~/.kube/config
    
        # Verify the config file is created
        cat ~/.kube/config

      # Deploy to Local Kubernetes using Rancher CLI
    - name: Deploy to Local Kubernetes
      run: |
          rancher kubectl apply -f deployment.yaml  # Apply the deployment file
          rancher kubectl apply -f service.yaml     # Apply the service file
          rancher kubectl get pods  # Verify the pods are running
